// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3uhfs_fnACiY6gLirBpAItTStWA64q_0',
    appId: '1:1071205724398:web:5eceecfdd079073a2dc3ff',
    messagingSenderId: '1071205724398',
    projectId: 'attendance-sys-uae',
    authDomain: 'attendance-sys-uae.firebaseapp.com',
    storageBucket: 'attendance-sys-uae.firebasestorage.app',
    measurementId: 'G-DYS64GF4Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAps1QUshY6ticZ1sB36MdByNwHir8LCg',
    appId: '1:1071205724398:android:c4410f4638a17b712dc3ff',
    messagingSenderId: '1071205724398',
    projectId: 'attendance-sys-uae',
    storageBucket: 'attendance-sys-uae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6VpfNjwwEU-FaUkluTdk3uV-MxfqwRbs',
    appId: '1:1071205724398:ios:f67854350111f1942dc3ff',
    messagingSenderId: '1071205724398',
    projectId: 'attendance-sys-uae',
    storageBucket: 'attendance-sys-uae.firebasestorage.app',
    iosClientId: '1071205724398-pcsdg8f34rbuvnu205tiejk3ubl9ptg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6VpfNjwwEU-FaUkluTdk3uV-MxfqwRbs',
    appId: '1:1071205724398:ios:f67854350111f1942dc3ff',
    messagingSenderId: '1071205724398',
    projectId: 'attendance-sys-uae',
    storageBucket: 'attendance-sys-uae.firebasestorage.app',
    iosClientId: '1071205724398-pcsdg8f34rbuvnu205tiejk3ubl9ptg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3uhfs_fnACiY6gLirBpAItTStWA64q_0',
    appId: '1:1071205724398:web:8074945227695bd12dc3ff',
    messagingSenderId: '1071205724398',
    projectId: 'attendance-sys-uae',
    authDomain: 'attendance-sys-uae.firebaseapp.com',
    storageBucket: 'attendance-sys-uae.firebasestorage.app',
    measurementId: 'G-YPZCT2QWKD',
  );
}
